#!/bin/sh

COMMIT_MSG_FILE="$1"

BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null)

if [ -n "$BRANCH_NAME" ]; then
  ISSUE_ID=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')

  if [ -n "$ISSUE_ID" ]; then
    PREFIX="$ISSUE_ID"
    OLD_MSG=$(cat "$COMMIT_MSG_FILE")

    if ! grep -q "$PREFIX" "$COMMIT_MSG_FILE"; then
      echo "[$PREFIX] $OLD_MSG" > "$COMMIT_MSG_FILE"
    fi
  fi
fi